# Generated by secman.py. Do not edit manually, unless you know what you are doing
#  SECRET KEYS file
#
#  Remember to keep copies of your secrets in a safe place
#
#  Note: Only lines not processed by secman.py will be those starting with "#"
#

MASTER_KEY_ENV = "MKEYPASSWD"
AAA = ""
AAA_ENCRYPTED = "gAAAAABmgudrTfdqIkspFsJIbKtnpqoyU6-2NP3tTC4sdvB3u6E6wNTdjs_mBqcvXdDuhU3SZgLGm2ZXmSf4iNKnpBsu6nImNg=="    # MKEYPASSWD,K1cAKQ==,2024-07-01 19:29:15
BBB = ""
BBB_ENCRYPTED = "gAAAAABmgudrgJYmjDtbUGHGFx8V7ON9ZYchrRXYiM4RZd95pNuyl8nJ5LBPDVh6dxrhoMiqITo4HEZ1pMPPkEgaVtZcvBq40A=="    # MKEYPASSWD,K1cAKQ==,2024-07-01 19:29:15
CCC_ENCRYPTED = "gAAAAABmfDNjOm18EwScoFchlD_M8yuXVxH0H0JQnpt4Wv9racjMHRdN-MbhE0OYzMIVS3yWPKydij3IKDjwb3OEIY50Fee4-Q=="  # MKEYPASSWD,K1cAKQ==,2024-06-26 17:27:31
