# Generated by secman.py. Do not edit manually, unless you know what you are doing
#  SECRET KEYS file
#
#  Remember to keep copies of your secrets in a safe place
#
#  Note: Only lines not processed by secman.py will be those starting with "#"
#

MASTER_KEY_ENV = "MKEYPASSWD"
AAA = ""
AAA_ENCRYPTED = "gAAAAABmfDNjcB_dUdvMkvrZXCHqTwB2k56wOPsbo-d0roY7igZJWRmjlAEZSyq91TaI4n-lA2Sp3z6OOZZTMTIxYUagPrUa6Q=="    #MKEYPASSWD,K1cAKQ==,2024-06-26 17:27:31
BBB = ""
BBB_ENCRYPTED = "gAAAAABmfDNjc1M35e5kxFYihMG-uYsK5iJYLnDSd3-Zr2raHZU0QJ5bqRkSucA4E79O7dNTOXRKu-Qn0DOBtOdUIDlP1BzSsQ=="    #MKEYPASSWD,K1cAKQ==,2024-06-26 17:27:31
CCC = ""
CCC_ENCRYPTED = "gAAAAABmfDNjOm18EwScoFchlD_M8yuXVxH0H0JQnpt4Wv9racjMHRdN-MbhE0OYzMIVS3yWPKydij3IKDjwb3OEIY50Fee4-Q=="    #MKEYPASSWD,K1cAKQ==,2024-06-26 17:27:31

