# Generated by secman.py. Do not edit manually, unless you know what you are doing
#  SECRET KEYS file
#
#  Remember to keep copies of your secrets in a safe place
#
#  Note: Only lines not processed by secman.py will be those starting with "#"
#

MASTER_KEY_ENV = "MKEYPASSWD"
AAA = ""
AAA_ENCRYPTED = "gAAAAABmfT10SMBUoOIAI97JAme-lbKkZbp44GeT9vboXXjpqG85JTMIU94QUJBfpa_MnfWJt1UzNPoJP8nciiL897YXTQpRdw=="    #MKEYPASSWD,K1cAKQ==,2024-06-27 12:22:45
BBB = ""
BBB_ENCRYPTED = "gAAAAABmfT11nHh5FoOwoL2eLsbBAss5CvV11871y1rkg2dwOvPK0-BRQuXD9OHnN1iIosO5fGsnvkzMB8SrEPiAeGDCWK8AIA=="    #MKEYPASSWD,K1cAKQ==,2024-06-27 12:22:45
CCC_ENCRYPTED = "gAAAAABmfDNjOm18EwScoFchlD_M8yuXVxH0H0JQnpt4Wv9racjMHRdN-MbhE0OYzMIVS3yWPKydij3IKDjwb3OEIY50Fee4-Q=="    #MKEYPASSWD,K1cAKQ==,2024-06-26 17:27:31
