# Generated by secman.py. Do not edit manually, unless you know what you are doing
#  SECRET KEYS file
#
#  Remember to keep copies of your secrets in a safe place
#
#  Note: Only lines not processed by secman.py will be those starting with "#"
#

MASTER_KEY_ENV = "MKEYPASSWD"
CCC_ENCRYPTED = "gAAAAABmfD8ejXpyM72dQWz61eJVR0Jb_FTg5e1ye7z33nR0AduyHZ9Os8AKREVNVGG0iXPSQu9xEtk3Ap5XpodmYqWZeIGN0w=="    #MKEYPASSWD,K1cAKQ==,2024-06-26 18:17:34
