# Generated by secman.py. Do not edit manually, unless you know what you are doing
#  SECRET KEYS file
#
#  Remember to keep copies of your secrets in a safe place
#
#  Note: Only lines not processed by secman.py will be those starting with "#"
#

MASTER_KEY_ENV = "MKEYPASSWD"
AAA = ""
AAA_ENCRYPTED = "gAAAAABmfTz9MnjEV1A0lfu0CLUMqHOno9BdZIOj8Hi9Euzv9kUmohNFpB9MVWQTUihpxUsIVrlJgGEF2KpS-pV8F6HrzJjNxA=="    #MKEYPASSWD,K1cAKQ==,2024-06-27 12:20:45
BBB = ""
BBB_ENCRYPTED = "gAAAAABmfTz9MXdUGfHxeCAD601I72E7xxTbu7L-fBz1F5LqVG-LUhz9jhoEhWljt3fgHEJXhgiXK2p8B0Dr8IownmNZbCYdtQ=="    #MKEYPASSWD,K1cAKQ==,2024-06-27 12:20:45
CCC_ENCRYPTED = "gAAAAABmfDNjOm18EwScoFchlD_M8yuXVxH0H0JQnpt4Wv9racjMHRdN-MbhE0OYzMIVS3yWPKydij3IKDjwb3OEIY50Fee4-Q=="    #MKEYPASSWD,K1cAKQ==,2024-06-26 17:27:31
