# Generated by secman.py. Do not edit manually, unless you know what you are doing
#  SECRET KEYS file
#
#  Remember to keep copies of your secrets in a safe place
#
#  Note: Only lines not processed by secman.py will be those starting with "#"
#

MASTER_KEY_ENV = "MKEYPASSWD"
BBB_ENCRYPTED = "gAAAAABmfD2ETyT_a8DeomcwV8awdyoHqCttaQ28vhWNAP-rMJfZCBsIiBz2ku8GcCCbyGmbj6dcPAQEOQFP3oo_DLTbYBGLtg=="    #MKEYPASSWD,K1cAKQ==,2024-06-26 17:27:31
CCC_ENCRYPTED = "gAAAAABmfDNjOm18EwScoFchlD_M8yuXVxH0H0JQnpt4Wv9racjMHRdN-MbhE0OYzMIVS3yWPKydij3IKDjwb3OEIY50Fee4-Q=="    #MKEYPASSWD,K1cAKQ==,2024-06-26 17:27:31
