# Generated by secman.py. Do not edit manually, unless you know what you are doing
#  SECRET KEYS file
#
#  Remember to keep copies of your secrets in a safe place
#
#  Note: Only lines not processed by secman.py will be those starting with "#"
#

MASTER_KEY_ENV = "MKEYPASSWD"
AAA = "hello"
BBB = "bye"
CCC = "secret"

