# Generated by secman.py. Do not edit manually, unless you know what you are doing
#  SECRET KEYS file
#
#  Remember to keep copies of your secrets in a safe place
#
#  Note: Only lines not processed by secman.py will be those starting with "#"
#

MASTER_KEY_ENV = "MKEYPASSWD"
AAA = ""
AAA_ENCRYPTED = "gAAAAABmfTzCf6C5eC90Oi2-nffsbxS3OP2zWiFhsXcrniKM1zhtxQf3G6gNxzaiZsmUl22zfN1sfm20h6hjldripg_wIlqQ9w=="    #MKEYPASSWD,K1cAKQ==,2024-06-27 12:19:46
BBB = ""
BBB_ENCRYPTED = "gAAAAABmfTzCh9G-U6NA7FBOrBVJivfAQAfryK6LA1-7Bc0lsEeETtUrVrfKvbRaVlA4RNkXLyodXBUsAknkusjOnRIT-6XR4A=="    #MKEYPASSWD,K1cAKQ==,2024-06-27 12:19:46
CCC_ENCRYPTED = "gAAAAABmfDNjOm18EwScoFchlD_M8yuXVxH0H0JQnpt4Wv9racjMHRdN-MbhE0OYzMIVS3yWPKydij3IKDjwb3OEIY50Fee4-Q=="    #MKEYPASSWD,K1cAKQ==,2024-06-26 17:27:31
